server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
  cloud:
    aws:
      credentials:
        secret-key: ${AWS_SECRET_KEY}
        access-key: ${AWS_ACCESS_KEY}
      region:
        static: eu-north-1
    servlet:
      multipart:
        max-file-size: 10MB
  debug: true

s3:
  pictures:
    bucket: plantsearch/
    type:
      image: dev-images
      sketch: dev-sketches
      markers: markers

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keyLength: 256
  token:
    secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
    expired: 3600000

nazariiboiko:
  openapi:
    dev-url: ${DEV_URL}